//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon_krasoti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientServices = new HashSet<ClientService>();
            this.ServicePhotoes = new HashSet<ServicePhoto>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public int DurationInSeconds { get; set; }
        public string Description { get; set; }
        public Nullable<double> Discount { get; set; }
        public string MainImagePath { get; set; }

        public string MainImagePathCorrected
        {
            
            get
            {
                string FolderPath = "Img/ServiceImages/";
                string Result1 = FolderPath + MainImagePath;
                switch (Result1)
                {
                    case "Img/ServiceImages/ бровки.png": Result1 = "Img/ServiceImages/brovky.png"; break;
                    case "Img/ServiceImages/ Гречишный массаж.jpg": Result1 = "Img/ServiceImages/grechishniy_massaj.jpg"; break;
                    case "Img/ServiceImages/ Декорирование нарощенных ресниц стразами.jpg": Result1 = "Img/ServiceImages/dekorirovanie_narochenih_resnic_strazami.jpg"; break;
                    case "Img/ServiceImages/ Депиляция воском.jpg": Result1 = "Img/ServiceImages/depilyaciya_voskom.jpg"; break;
                    case "Img/ServiceImages/ Демакияж.jpg": Result1 = "Img/ServiceImages/demakiyaj.jpg"; break;
                    case "Img/ServiceImages/ Европейский маникюр.jpg": Result1 = "Img/ServiceImages/evropeyskiy_manikur.jpg"; break;
                    case "Img/ServiceImages/ ИК-сауна.jpg": Result1 = "Img/ServiceImages/IK-sauna.jpg"; break;
                    case "Img/ServiceImages/ Классический маникюр.png": Result1 = "Img/ServiceImages/klasicheskiy_manikur.png"; break;
                    case "Img/ServiceImages/ Комбинированный маникюр.jpg": Result1 = "Img/ServiceImages/kombinirovanniy_manikur.jpg"; break;
                    case "Img/ServiceImages/ Контурная пластика.jpg": Result1 = "Img/ServiceImages/kotyrnaya_plastika.jpg"; break;
                    case "Img/ServiceImages/ массаж.jpg": Result1 = "Img/ServiceImages/massaj.jpg"; break;
                    case "Img/ServiceImages/ Мезотерапия.jpg": Result1 = "Img/ServiceImages/mezoterapiya.jpg"; break;
                    case "Img/ServiceImages/ Моделирование ресниц.jpg": Result1 = "Img/ServiceImages/modelirovanie_resnic.jpg"; break;
                    case "Img/ServiceImages/ ногти.png": Result1 = "nogty.png"; break;
                    case "Img/ServiceImages/ Окрашивание бровей.jpg": Result1 = "Img/ServiceImages/okrashivanie_brovey.jpg"; break;
                    case "Img/ServiceImages/ Парафинотерапия.jpg": Result1 = "Img/ServiceImages/parafinoterapiya.jpg"; break;
                    case "Img/ServiceImages/ Покрытие ногтей гель-лаком.jpg": Result1 = "Img/ServiceImages/pokritie_nogtey_gel_lakom.jpg"; break;
                    case "Img/ServiceImages/ Полировка ногтей.jpg": Result1 = "Img/ServiceImages/polirovka_nogtey.jpg"; break;
                    case "Img/ServiceImages/ Прессотерапия.jpg": Result1 = "Img/ServiceImages/pressoterapiya.jpg"; break;
                    case "Img/ServiceImages/ Прокол ушей пистолетом.png": Result1 = "Img/ServiceImages/prokol_yshey_pistoletom.png"; break;
                    case "Img/ServiceImages/ Ресницы.png": Result1 = "Img/ServiceImages/resnicy.png"; break;
                    case "Img/ServiceImages/ Снятие ресниц.jpg": Result1 = "Img/ServiceImages/snyatie_resnic.jpg"; break;
                    case "Img/ServiceImages/ Стоун-терапия.jpg": Result1 = "Img/ServiceImages/stoun_terapiya.jpg"; break;
                    case "Img/ServiceImages/ стрижка.png": Result1 = "Img/ServiceImages/strijka.png"; break;
                    case "Img/ServiceImages/ Укрепление ногтей гелем.jpg": Result1 = "Img/ServiceImages/ykreplenie_nogtey_gelem.jpg"; break;
                    case "Img/ServiceImages/ Шугаринг.jpg": Result1 = "Img/ServiceImages/shygaring.jpg"; break;
                    case "Img/ServiceImages/ Экспресс-педикюр.jpg": Result1 = "Img/ServiceImages/ekspress_pedikyr.jpg"; break;
                    case "Img/ServiceImages/ Экспресс SPA.png": Result1 = "Img/ServiceImages/ekspress_spa.png"; break;

                }
                char[] r1 = Result1.ToCharArray();
                string result2 = "";
                for (int i = 0; i < r1.Length; i++)
                {
                    if (!(r1[i].Equals(' ')))
                    {
                        result2 += Convert.ToString(r1[i]);
                    }
                }

                return result2;
            }
        }

        public int CostWithDiscount
        {
            get
            {
                if (Discount != null)
                {
                    return Convert.ToInt32(Cost) * Convert.ToInt32(Discount);
                }
                else
                {
                    return Convert.ToInt32(Cost);
                }
            }
        }

        public int DurationInMinutes
        {
            get
            {
                return DurationInSeconds / 60;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhotoes { get; set; }
    }
}
